  - hosts: all
    connection: local
    become: true
    become_user: root
    roles: base
  
  - hosts: all
    connection: local
    become: true
    become_user: root
    roles: kubernetes_prerequisites

  - hosts: all
    connection: local
    become: true
    become_user: root
    roles: docker_installation

  - hosts: all
    connection: local
    become: true
    become_user: root
    roles: kubernetes_installation

  - hosts: all
    connection: local
    become: true
    become_user: root
    roles: kubernetes_configuration

