---
- name: Install Kubernetes on a server
  connection: local
  become: true
  become_user: root

  vars:
    kubernetes_version: "1.31"

  pre_tasks:
    - name: Ensure pip is installed on Debian-based systems
      ansible.builtin.apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure pip is installed on Red Hat-based systems
      ansible.builtin.yum:
        name: python3-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure kubernetes Python library is installed
      ansible.builtin.pip:
        name: kubernetes
        state: present
      become: yes

  roles:
    - kubernetes_prerequisites
    - docker_installation
    - kubernetes_installation
    - kubernetes_configuration
