---
- name: Ensure necessary packages are installed on Debian-based systems
  ansible.builtin.shell: |
    apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates
  when: ansible_os_family == "Debian"
  become: true

- name: Add Docker GPG key on Debian-based systems
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  when: ansible_os_family == "Debian"
  become: true

- name: Add Docker repository on Debian-based systems
  ansible.builtin.shell: |
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  when: ansible_os_family == "Debian"
  become: true

- name: Ensure necessary packages are installed on Red Hat-based systems
  yum:
    name:
      - curl
      - gnupg2
      - yum-utils
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Add Docker GPG key on Red Hat-based systems
  ansible.builtin.rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg
  when: ansible_os_family == "RedHat"

- name: Add Docker repository on Red Hat-based systems
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: 1
  when: ansible_os_family == "RedHat"

- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: true

- name: Install Docker on Debian-based systems
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  when: docker_check.failed and ansible_os_family == "Debian"

- name: Install Docker on Red Hat-based systems
  yum:
    name: docker-ce
    state: present
    update_cache: yes
  when: docker_check.failed and ansible_os_family == "RedHat"
