---
- name: Remove Podman on Red Hat-based systems
  yum:
    name: podman
    state: absent
  when: ansible_os_family == "RedHat"

- name: Add Docker repository on Debian-based systems
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository on Red Hat-based systems
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: 1
  when: ansible_os_family == "RedHat"

- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: true

- name: Install Docker on Debian-based systems
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  when: docker_check.failed and ansible_os_family == "Debian"

- name: Install Docker on Red Hat-based systems
  yum:
    name: docker-ce
    state: present
    update_cache: yes
  when: docker_check.failed and ansible_os_family == "RedHat"
