- name: Initialize Kubernetes
  shell: |
    sudo kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --control-plane-endpoint={{ ansible_default_ipv4.address }} --apiserver-cert-extra-sans={{ ansible_default_ipv4.address }} --pod-network-cidr=172.16.0.0/16 --upload-certs

- name: create .kube folder
  become: true
  become_user: root
  file:
    path: ~/.kube
    state: directory

- name: copy files to kube folder
  become: true
  become_user: root
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config

- name: change ownership of the kube config
  file:
    path: $HOME/.kube/config
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: remove taints
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-

- name: Install Calico
  shell: |
    curl https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml -O
    kubectl apply -f calico.yaml

- name: Get the token for joining the nodes with Kuberentes master.
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command
- debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  become: false
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
  #local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest=".ansible/pull/master/roles/initkubernetes/files/kubernetes_join_command" mode=0777
- name: in which folder am I
  debug:
    msg: pwd




