---
- name: Check if kubectl is installed
  stat:
    path: /usr/bin/kubectl
  register: kubectl_check
- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_os_family == "Debian"
  
- name: Add kubernetes Repo to Debian/Ubuntu part 1
  #shell: >
  #curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo
  #apt-key add -
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when:
  - ansible_distribution in ["Debian", "Ubuntu"]
- name: Add kubernetes Repo to Debian/Ubuntu part 2
  shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  when:
  - ansible_distribution in ["Debian", "Ubuntu"]
- name: Add kubernetes Repo to Debian/Ubuntu part 3
  shell: apt-get update
  when:
  - ansible_distribution in ["Debian", "Ubuntu"]
- name: Install kubernetes on Debian/Ubuntu
  shell: apt install -y kubelet={{ ubuntu_kubernetes_version }} kubeadm={{ ubuntu_kubernetes_version }} kubectl={{ ubuntu_kubernetes_version }}
  when:
  - not kubectl_check.stat.exists and ansible_os_family == "Debian"
- name: before init on Ubuntu
  shell: "sudo systemctl daemon-reload \nsudo systemctl restart docker\nsudo systemctl enable docker\nlsmod | grep br_netfilter\nsudo systemctl enable kubelet\nsudo kubeadm config images pull\nsudo containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1\nsudo sed -i 's/SystemdCgroup \\= false/SystemdCgroup \\= true/g' /etc/containerd/config.toml\nsystemctl restart containerd\n"
  when:
  - ansible_distribution in ["Debian", "Ubuntu"]
- name: Add Kubernetes repository on Red Hat-based systems
  yum_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: https://pkgs.k8s.io/core:/stable:/{{ redhat_version }}/rpm/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/{{ redhat_version }}/rpm/Release.key
  when: ansible_os_family == "RedHat"




