---
- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output
  when: not kubectl_check.stat.exists
  
- name: create .kube folder
  shell: mkdir -p $HOME/.kube
  when: kubeadm_output is succeeded
  
- name: Set up kubeconfig for the root user
  copy:
    dest: /root/.kube/config
    content: "{{ lookup('file', '/etc/kubernetes/admin.conf') }}"
  when: kubeadm_output is succeeded

- name: remove taints
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-
   when: kubeadm_output is succeeded
   
- name: Install Pod network (Calico)
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: kubeadm_output is succeeded

- name: Get the token for joining the nodes with Kuberentes master.
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command
- debug:
    msg: "{{ kubernetes_join_command.stdout }}"
 when: kubeadm_output is succeeded
 
- name: Copy join command to local file.
  become: false
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
   when: kubeadm_output is succeeded
   
- name: Copy that join command to local server
  run_once: true
  delegate_to: ubuntu
  fetch:
    src: /tmp/kubernetes_join_command
    dest: /tmp/
    flat: yes
   when: kubeadm_output is succeeded


- name: Join the Worker nodes with the master.
  become: true
  become_method: sudo
  become_user: root
  command: sh /tmp/kubernetes_join_command
  register: joined_or_not
  when: kubeadm_output is succeeded
