---
- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output
  when: not kubectl_check.stat.exists
  
- name: create .kube folder
  shell: mkdir -p $HOME/.kube
  when: kubeadm_output is succeeded
  
- name: Set up kubeconfig for the root user
  copy:
    dest: /root/.kube/config
    content: "{{ lookup('file', '/etc/kubernetes/admin.conf') }}"
  when: kubeadm_output is succeeded

- name: Check if taint exists on nodes
  ansible.builtin.shell: |
    kubectl get nodes -o json | jq -c '.items[] | select(.spec.taints[] | contains({key:"node-role.kubernetes.io/control-plane", effect:"NoSchedule"}))'
  register: taint_check
  ignore_errors: true
  changed_when: false

- name: Check taint status
  ansible.builtin.debug:
    msg: "Taints are removed"
  when: taint_check.rc == 0

- name: Remove taints if they exist
  ansible.builtin.shell: |
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-:NoSchedule-
  when: taint_check.rc == 0
  ignore_errors: true
  changed_when: false
   
- name: Install Pod network (Calico)
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: kubeadm_output is succeeded


 

