---
- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output
  when: not kubectl_check.stat.exists
  
- name: create .kube folder
  shell: mkdir -p $HOME/.kube
  when: kubeadm_output is succeeded
  
- name: Set up kubeconfig for the root user
  copy:
    dest: /root/.kube/config
    content: "{{ lookup('file', '/etc/kubernetes/admin.conf') }}"
  when: kubeadm_output is succeeded

- name: remove taints
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  when: kubeadm_output is succeeded
   
- name: Install Pod network (Calico)
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: kubeadm_output is succeeded


 

