---
- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output
  when: not kubectl_check.stat.exists

- name: Set up kubeconfig for the root user
  copy:
    dest: /root/.kube/config
    content: "{{ lookup('file', '/etc/kubernetes/admin.conf') }}"
  when: kubeadm_output is succeeded

- name: Install Pod network (Calico)
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: kubeadm_output is succeeded

- name: Join worker nodes to cluster
  command: "{{ kubeadm_output.stdout_lines[-1] }}"
  when: kubeadm_output is succeeded

