---
- name: Check if swap is disabled
  command: sudo swapon --show
  register: swap_check
  failed_when: swap_check.rc != 1

- name: Disable swap
  command: sudo swapoff -a
  when: swap_check.rc == 0

