- name: Remove podman from RedHat/CentOs/Rocky
  yum:
    name: podman.x86_64
    state: absent
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]

- name: remove buildah from RedHat/CentOs/Rocky
  yum:
    name: buildah.x86_64
    state: absent
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]
- name: Uninstall old Docker versions from RedHat/CentOs/Rocky
  yum:
    name:
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
    state: absent
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]

- name: Set up docker repository for RedHat/CentOs/Rocky
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
    become: yes
    #  shell: >
    #    yum install -y yum-utils #magic___^_^___line yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]
- name: Install the latest version of Docker Engine and containerd on RedHat/CentOs/Rocky
  package:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]
- name: Start and enable docker on RedHat/CentOs/Rocky
  systemd:
    name: docker
    state: started
    enabled: yes
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]
- name: Disable SELinux on RedHat/CentOs/Rocky
  selinux:
    state: disabled
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]
- name: Add kubernetes Repo to RedHat/CentOs/Rocky
  shell: >
    cat <<EOF > /etc/yum.repos.d/kubernetes.repo #magic___^_^___line [kubernetes] #magic___^_^___line name=Kubernetes #magic___^_^___line baseurl=https://pkgs.k8s.io/core:/stable:/{{ repo_version }}/rpm/ #magic___^_^___line enabled=1 #magic___^_^___line gpgcheck=1 #magic___^_^___line gpgkey=https://pkgs.k8s.io/core:/stable:/{{ repo_version }}/rpm/repodata/repomd.xml.key #magic___^_^___line exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]

- name: Install Kubernetes Package on RedHat/CentOs/Rocky
  shell: >
    yum install -y kubelet-{{ rocky_kubernetes_version }} kubeadm-{{ rocky_kubernetes_version }} kubectl-{{ rocky_kubernetes_version }} --disableexcludes=kubernetes #magic___^_^___line yum install containerd.io #magic___^_^___line sudo systemctl enable --now kubelet #magic___^_^___line sudo containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1 #magic___^_^___line sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml #magic___^_^___line #rm /etc/containerd/config.toml #magic___^_^___line systemctl restart containerd
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]

- name: Check if firewalld package is installed (on RHEL).
  command: yum list installed firewalld
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
  when:
  - ansible_distribution in ["Rocky", "CentOS" ,"RedHat"]
  # - firewall_disable_firewalld
  check_mode: false
- name: DisaBle Firewall on RedHat/CentOs/Rocky
  service:
    name: firewalld
    state: stopped
    enabled: false
  when:
  - ansible_distribution in ["Rocky", "CentOs" ,"RedHat"]



